{"uid":"e45e945da4e9942e","name":"Successful login","fullName":"Tests.test_Login.TestLogin#test_2","historyId":"ce04ae5da7eb2137a09a57b9b398f855","time":{"start":1728037309327,"stop":1728037310038,"duration":711},"status":"failed","statusMessage":"AssertionError: FAILURE: \ntest_Login.py:57 in test_2() -> check_with_screenshot(\nBaseClass.py:16 in check_with_screenshot() -> with check, allure.step(message):\nBaseClass.py:23 in check_with_screenshot -> assert cond\nAssertionError\n\n\n------------------------------------------------------------\nFailed Checks: 1","statusTrace":"FAILURE: \ntest_Login.py:57 in test_2() -> check_with_screenshot(\nBaseClass.py:16 in check_with_screenshot() -> with check, allure.step(message):\nBaseClass.py:23 in check_with_screenshot -> assert cond\nAssertionError\n\n\n------------------------------------------------------------\nFailed Checks: 1","flaky":false,"newFailed":true,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"setup_reporting_directories","time":{"start":1728037285989,"stop":1728037285990,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1728037307944,"stop":1728037308165,"duration":221},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: FAILURE: \ntest_Login.py:57 in test_2() -> check_with_screenshot(\nBaseClass.py:16 in check_with_screenshot() -> with check, allure.step(message):\nBaseClass.py:23 in check_with_screenshot -> assert cond\nAssertionError\n\n\n------------------------------------------------------------\nFailed Checks: 1","statusTrace":"FAILURE: \ntest_Login.py:57 in test_2() -> check_with_screenshot(\nBaseClass.py:16 in check_with_screenshot() -> with check, allure.step(message):\nBaseClass.py:23 in check_with_screenshot -> assert cond\nAssertionError\n\n\n------------------------------------------------------------\nFailed Checks: 1","steps":[{"name":"The app logo is visible after login","time":{"start":1728037309497,"stop":1728037309497,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"The app logo text is correct after login","time":{"start":1728037309515,"stop":1728037309896,"duration":381},"status":"failed","statusMessage":"AssertionError\n","statusTrace":"  File \"/home/runner/work/test-repo/test-repo/Common/BaseClass.py\", line 23, in check_with_screenshot\n    assert cond\n           ^^^^\n","steps":[],"attachments":[{"uid":"3158be903510cec5","name":"screenshot","source":"3158be903510cec5.png","type":"image/png","size":336923}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},{"name":"The items are visible after login","time":{"start":1728037309909,"stop":1728037309909,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":3,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"driver::0","time":{"start":1728037310040,"stop":1728037310106,"duration":66},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"feature","value":"Login"},{"name":"severity","value":"critical"},{"name":"parentSuite","value":"Tests"},{"name":"suite","value":"test_Login"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"fv-az792-499"},{"name":"thread","value":"2356-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"Tests.test_Login"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"driver","value":"'Chrome'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":1,"broken":4,"skipped":0,"passed":3,"unknown":0,"total":8},"items":[{"uid":"af5f54533bc38f20","reportUrl":"https://Simeon-Zografov.github.io/test-repo/10//#testresult/af5f54533bc38f20","status":"passed","time":{"start":1728024567996,"stop":1728024569623,"duration":1627}},{"uid":"4d53f19ba39fe874","reportUrl":"https://Simeon-Zografov.github.io/test-repo/9//#testresult/4d53f19ba39fe874","status":"passed","time":{"start":1728033368804,"stop":1728033369165,"duration":361}},{"uid":"88e5af9c3e8210d2","reportUrl":"https://Simeon-Zografov.github.io/test-repo/5//#testresult/88e5af9c3e8210d2","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to locate or obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1728032230068,"stop":1728032230068,"duration":0}},{"uid":"b86e7da5d64794d4","reportUrl":"https://Simeon-Zografov.github.io/test-repo/4//#testresult/b86e7da5d64794d4","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to locate or obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1728031969077,"stop":1728031969077,"duration":0}},{"uid":"c28470226b76f59d","reportUrl":"https://Simeon-Zografov.github.io/test-repo/3//#testresult/c28470226b76f59d","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to locate or obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1728031301088,"stop":1728031301088,"duration":0}},{"uid":"7de2e884d4c4cbc8","reportUrl":"https://Simeon-Zografov.github.io/test-repo/2//#testresult/7de2e884d4c4cbc8","status":"broken","statusDetails":"OSError: [Errno 8] Exec format error: '/home/runner/.wdm/drivers/chromedriver/linux64/129.0.6668.89/chromedriver-linux64/THIRD_PARTY_NOTICES.chromedriver'","time":{"start":1728030516968,"stop":1728030516968,"duration":0}},{"uid":"6caa792da916a0ca","status":"passed","time":{"start":1728024567996,"stop":1728024569623,"duration":1627}}]},"tags":[]},"source":"e45e945da4e9942e.json","parameterValues":["'Chrome'"]}